apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-back
  template:
    metadata:
      labels:
        app: app-back
    spec:
      containers:
      - name: app-back
        image: jovan99djokic/app_back_dev:{{VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: backend-storage
          mountPath: /app/instance
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1