apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-back
  namespace: dev-app1  # Ensure this matches your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-back
  template:
    metadata:
      labels:
        app: app-back
    spec:
      containers:
      - name: app-back
        image: jovan99djokic/app_back_dev:{{VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/instance  # Path inside the container
          name: backend-storage
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
