apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-back
  template:
    metadata:
      labels:
        app: app-back
    spec:
      containers:
      - name: app-back
        image: jovan99djokic/app_back_dev:{{VERSION}}  # Replace with actual version
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/app/instance"
          name: backend-pv
      volumes:  # Add this section to define the volume
      - name: backend-pv
        persistentVolumeClaim:
          claimName: backend-pvc  # Replace with the name of your PVC
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1