apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:  # This is for testing purposes; use actual storage in production
    path: /tmp/hostpath-provisioner/dev-app1/backend-pvc
