apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:  # This is for testing purposes; use actual storage in production
    path: /tmp/hostpath-provisioner/dev-app1/backend-pvc
