apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: dev-app1  # Ensure this matches your namespace
spec:
  storageClassName: app  # Use the default storage class for dynamic provisioning
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
