apiVersion: v1
kind: Service
metadata:
  name: app-back
spec:
  type: LoadBalancer
  selector:
    app: app-back
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
