name: Docker Image CI

on:
  push:
    branches: [ "Development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: jovan99djokic/app_back_dev:${{ env.SHORT_SHA }}
        labels: |
          org.opencontainers.image.revision=${{ env.SHORT_SHA }}

    - name: Implement SHA in DeploymentAppBackDev.yaml
      run: sed -i "s/__SHA__/${{ env.SHORT_SHA }}/g" ./DeploymentAppBackDev.yaml

    - name: Create .kube directory
      run: mkdir -p $HOME/.kube

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Copy Minikube Certificates
      run: |
        mkdir -p $HOME/.minikube/profiles/minikube
        cp /home/teezer/.minikube/* $HOME/.minikube/profiles/minikube/

    - name: Apply Kubernetes deployment
      run: kubectl apply -f ./DeploymentAppBackDev.yaml
