name: Docker Image CI

on:
  push:
    branches: [ "Development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine version number
      id: version
      run: echo "::set-output name=version::1.${{ github.run_number }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: jovan99djokic/app_front_dev:${{ steps.version.outputs.version }}

    - name: Log out from Docker Hub
      run: docker logout
